from setuptools import setup, find_packages

setup(name='ballpark',
    description='Better human-readable numbers.',
    long_description=open('README.rst').read(),
    author='Stijn Debrouwere',
    author_email='stijn@debrouwere.org',
    url='https://github.com/debrouwere/python-ballpark/',
    download_url='https://www.github.com/debrouwere/python-ballpark/tarball/master',
    version='1.1.1',
    license='ISC',
    packages=find_packages(),
    keywords='human numbers format notation scientific engineering',
    install_requires=[],
    test_suite='ballpark.tests',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: ISC License (ISCL)',
        'Operating System :: OS Independent',
        'Topic :: Scientific/Engineering :: Information Analysis',
        'Topic :: Utilities',        
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        ],
    )
